name: code_generator
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.8
  shared_preferences: ^2.5.2
  provider: ^6.1.2
  permission_handler: ^11.4.0
  path_provider: ^2.1.5
  barcode_widget: ^2.0.4
  intl: ^0.20.2
  font_awesome_flutter: ^10.8.0
  crystal_navigation_bar: any
  # flutter_image_gallery_saver: ^0.0.2
  barcode_scan2: ^4.5.0
  pdf: ^3.11.3
  printing: ^5.14.2
  # gal: ^2.3.1
  # flutter_file_dialog: ^3.0.2


dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.14.3

flutter_launcher_icons:
  android: true
  ios: true
  remove_alpha_ios: true
  image_path: "assets/imgs/app_icon.png"

flutter:

 
  uses-material-design: true

  
  fonts:
    - family: Cairo
      fonts:
        - asset: assets/fonts/Cairo-Regular.ttf
    - family: Cairo-Bold
      fonts:
        - asset: assets/fonts/Cairo-Bold.ttf
